//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBHO_Data.EntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Orders = new HashSet<Order>();
            this.Withdrawals = new HashSet<Withdrawal>();
        }
    
        public int MemberId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string TelephoneNo { get; set; }
        public string Occupation { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string BirthPlace { get; set; }
        public string Citizenship { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string PresentAddress { get; set; }
        public string ProvincialAddress { get; set; }
        public int ParentId { get; set; }
        public int SponsorId { get; set; }
        public string HierarchyCode { get; set; }
        public string MemberCode { get; set; }
        public Nullable<System.DateTime> DateJoined { get; set; }
        public int RoleId { get; set; }
        public string Picture { get; set; }
        public string Type { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApprovedDate { get; set; }
        public string RecState { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> LastLoggedIn { get; set; }
        public Nullable<bool> IsFreeAccount { get; set; }
        public string PaymentType { get; set; }
        public string CashNote { get; set; }
        public string BankBranch { get; set; }
        public string DepositNo { get; set; }
        public Nullable<System.DateTime> DateDeposited { get; set; }
    
        public virtual Role Role { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Withdrawal> Withdrawals { get; set; }
    }
}
