//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBHO_Data.EntityFrameworks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Withdrawal
    {
        public int WithdrawId { get; set; }
        public int MemberId { get; set; }
        public decimal Amount { get; set; }
        public string ChequeNo { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
