//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GBHO_Data.EntityFrameworks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GBHODBEntities : DbContext
    {
        public GBHODBEntities()
            : base("name=GBHODBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BinaryIncomeAll> BinaryIncomeAlls { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<Setting> Settings { get; set; }
        public DbSet<Withdrawal> Withdrawals { get; set; }
    
        [EdmFunction("GBHODBEntities", "GetBinaryIncome")]
        public virtual IQueryable<GetBinaryIncome_Result> GetBinaryIncome(string hcode)
        {
            var hcodeParameter = hcode != null ?
                new ObjectParameter("hcode", hcode) :
                new ObjectParameter("hcode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetBinaryIncome_Result>("[GBHODBEntities].[GetBinaryIncome](@hcode)", hcodeParameter);
        }
    
        [EdmFunction("GBHODBEntities", "GetPairBonus")]
        public virtual IQueryable<GetPairBonus_Result> GetPairBonus(Nullable<int> memberId, Nullable<System.DateTime> dt, Nullable<int> refval, Nullable<int> pair, string hCode)
        {
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            var refvalParameter = refval.HasValue ?
                new ObjectParameter("refval", refval) :
                new ObjectParameter("refval", typeof(int));
    
            var pairParameter = pair.HasValue ?
                new ObjectParameter("pair", pair) :
                new ObjectParameter("pair", typeof(int));
    
            var hCodeParameter = hCode != null ?
                new ObjectParameter("hCode", hCode) :
                new ObjectParameter("hCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<GetPairBonus_Result>("[GBHODBEntities].[GetPairBonus](@memberId, @dt, @refval, @pair, @hCode)", memberIdParameter, dtParameter, refvalParameter, pairParameter, hCodeParameter);
        }
    
        public virtual ObjectResult<BinaryIncome_Result> BinaryIncome(Nullable<int> memberID, Nullable<System.DateTime> dt)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BinaryIncome_Result>("BinaryIncome", memberIDParameter, dtParameter);
        }
    
        public virtual ObjectResult<GetAllForReceiving_Result> GetAllForReceiving()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllForReceiving_Result>("GetAllForReceiving");
        }
    
        public virtual ObjectResult<GetAllOrders_Result> GetAllOrders(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrders_Result>("GetAllOrders", usernameParameter);
        }
    
        public virtual ObjectResult<GetAllOrdersPending_Result> GetAllOrdersPending(Nullable<int> memberID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllOrdersPending_Result>("GetAllOrdersPending", memberIDParameter);
        }
    
        public virtual ObjectResult<GetCart_Result> GetCart(Nullable<int> memberID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCart_Result>("GetCart", memberIDParameter);
        }
    
        public virtual ObjectResult<GetMyOrders_Result> GetMyOrders(Nullable<int> memberID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetMyOrders_Result>("GetMyOrders", memberIDParameter);
        }
    
        public virtual ObjectResult<GetOrderDetails_Result> GetOrderDetails(Nullable<long> orderId)
        {
            var orderIdParameter = orderId.HasValue ?
                new ObjectParameter("OrderId", orderId) :
                new ObjectParameter("OrderId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOrderDetails_Result>("GetOrderDetails", orderIdParameter);
        }
    
        public virtual ObjectResult<GetPairs_Result> GetPairs(string hierarchyCode, Nullable<System.DateTime> dT)
        {
            var hierarchyCodeParameter = hierarchyCode != null ?
                new ObjectParameter("HierarchyCode", hierarchyCode) :
                new ObjectParameter("HierarchyCode", typeof(string));
    
            var dTParameter = dT.HasValue ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetPairs_Result>("GetPairs", hierarchyCodeParameter, dTParameter);
        }
    
        public virtual ObjectResult<GroupBonus_Result> GroupBonus(Nullable<int> memberID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GroupBonus_Result>("GroupBonus", memberIDParameter);
        }
    
        public virtual ObjectResult<OrderReports_Result> OrderReports(string admin, Nullable<System.DateTime> dt)
        {
            var adminParameter = admin != null ?
                new ObjectParameter("admin", admin) :
                new ObjectParameter("admin", typeof(string));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderReports_Result>("OrderReports", adminParameter, dtParameter);
        }
    
        public virtual ObjectResult<PairingBonus_Result> PairingBonus(Nullable<int> memberID)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PairingBonus_Result>("PairingBonus", memberIDParameter);
        }
    
        public virtual int ProcessRebatesCleanUp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessRebatesCleanUp");
        }
    
        public virtual int ProcessRebatesReport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProcessRebatesReport");
        }
    
        public virtual ObjectResult<ProcessRebatesReportStatus_Result> ProcessRebatesReportStatus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcessRebatesReportStatus_Result>("ProcessRebatesReportStatus");
        }
    
        public virtual ObjectResult<Rebates_Result> Rebates(Nullable<System.DateTime> dt, Nullable<bool> hasGroupBonus)
        {
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            var hasGroupBonusParameter = hasGroupBonus.HasValue ?
                new ObjectParameter("hasGroupBonus", hasGroupBonus) :
                new ObjectParameter("hasGroupBonus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rebates_Result>("Rebates", dtParameter, hasGroupBonusParameter);
        }
    
        public virtual ObjectResult<Rebates2_Result> Rebates2(Nullable<System.DateTime> dt, Nullable<bool> hasGroupBonus)
        {
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            var hasGroupBonusParameter = hasGroupBonus.HasValue ?
                new ObjectParameter("hasGroupBonus", hasGroupBonus) :
                new ObjectParameter("hasGroupBonus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rebates2_Result>("Rebates2", dtParameter, hasGroupBonusParameter);
        }
    
        public virtual ObjectResult<RebatesByMember_Result> RebatesByMember(Nullable<System.DateTime> dt, Nullable<bool> hasGroupBonus, Nullable<int> memberId)
        {
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            var hasGroupBonusParameter = hasGroupBonus.HasValue ?
                new ObjectParameter("hasGroupBonus", hasGroupBonus) :
                new ObjectParameter("hasGroupBonus", typeof(bool));
    
            var memberIdParameter = memberId.HasValue ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RebatesByMember_Result>("RebatesByMember", dtParameter, hasGroupBonusParameter, memberIdParameter);
        }
    
        public virtual ObjectResult<RebatesReport_Result> RebatesReport(Nullable<int> memberID, Nullable<System.DateTime> dt, Nullable<bool> hasGroupBonus)
        {
            var memberIDParameter = memberID.HasValue ?
                new ObjectParameter("MemberID", memberID) :
                new ObjectParameter("MemberID", typeof(int));
    
            var dtParameter = dt.HasValue ?
                new ObjectParameter("dt", dt) :
                new ObjectParameter("dt", typeof(System.DateTime));
    
            var hasGroupBonusParameter = hasGroupBonus.HasValue ?
                new ObjectParameter("hasGroupBonus", hasGroupBonus) :
                new ObjectParameter("hasGroupBonus", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RebatesReport_Result>("RebatesReport", memberIDParameter, dtParameter, hasGroupBonusParameter);
        }
    
        public virtual ObjectResult<Nullable<System.DateTime>> RebatesReportLastUpdate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<System.DateTime>>("RebatesReportLastUpdate");
        }
    }
}
